# Generated by Django 2.2.7 on 2019-11-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('rough_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('postcode', models.TextField(max_length=8)),
            ],
        ),
    ]
