# Generated by Django 2.2.7 on 2019-11-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='postcode',
            field=models.CharField(max_length=8),
        ),
    ]
