# Generated by Django 2.2.7 on 2019-11-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_auto_20191113_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='rough_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
