# Generated by Django 2.2.7 on 2019-11-14 10:03

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_auto_20191113_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='rough_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'GBP £')], default='GBP', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='rough_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='GBP', max_digits=10, null=True),
        ),
    ]
